#!/usr/bin/env bash
# local-e2e-check.sh — verify, on your own machine, the two things this repo
# automates for cloud: gcp:
#
#   1. discovery -> validated agent-graph.yml -> six scaffolded agents
#
#   2. discovery answers -> real generated Terraform (store-*.tf,
#      platform-*.tf, service-<name>.tf via junction/terraform_generator.py,
#      wired into the CLI through scaffold.py's collect_files()) ->
#      terraform init / fmt / validate / plan against a real cloud provider
#      schema. Roadmap item #7 (docs/wiki/Roadmap-and-Open-Items.md) is
#      resolved for GCP; AWS/Azure still return no .tf files.
#
# `plan` is EXPECTED to fail at "could not find default credentials" unless
# you pass a real GCP project with -p — that failure is treated as a PASS
# here, because it proves the HCL is correct up to the point where real
# cloud access is needed. Any other plan failure is a real bug and fails
# the script.
#
# Usage:
#   ./scripts/local-e2e-check.sh                          # domain=e2e-check, no real project
#   ./scripts/local-e2e-check.sh -d my-idea                # a different domain name
#   ./scripts/local-e2e-check.sh -d my-idea -p my-gcp-proj  # try a REAL plan against your project
#                                                            # (needs `gcloud auth application-default login` first)
#
# Requires: python3, pip, terraform (in PATH or set $TERRAFORM_BIN).

set -euo pipefail

DOMAIN="e2e-check"
PROJECT_ID=""
KEEP=false

while getopts "d:p:k" opt; do
  case "$opt" in
    d) DOMAIN="$OPTARG" ;;
    p) PROJECT_ID="$OPTARG" ;;
    k) KEEP=true ;;
    *) echo "Usage: $0 [-d domain] [-p gcp_project_id] [-k keep-workdir]"; exit 1 ;;
  esac
done

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TERRAFORM_BIN="${TERRAFORM_BIN:-terraform}"
WORKDIR="$(mktemp -d /tmp/iac-e2e-check.XXXXXX)"
VENV="$WORKDIR/venv"
TARGET="$WORKDIR/$DOMAIN"

pass() { printf '\033[32m✓ %s\033[0m\n' "$1"; }
fail() { printf '\033[31m✗ %s\033[0m\n' "$1"; exit 1; }
step() { printf '\n\033[1m── %s ──\033[0m\n' "$1"; }

cleanup() {
  if [ "$KEEP" = true ]; then
    echo "Kept workdir for inspection: $WORKDIR"
  else
    rm -rf "$WORKDIR"
  fi
}
trap cleanup EXIT

command -v "$TERRAFORM_BIN" >/dev/null 2>&1 || fail "terraform not found in PATH (set TERRAFORM_BIN=/path/to/terraform)"
command -v python3 >/dev/null 2>&1 || fail "python3 not found"

# ─── Stage 1: discovery -> validated graph -> agents ────────────────────────────

step "1/5 — Build junction from this checkout ($(cd "$REPO_ROOT" && git branch --show-current 2>/dev/null || echo 'no git'))"
python3 -m venv "$VENV"
"$VENV/bin/pip" install -q --upgrade pip
"$VENV/bin/pip" install -q "$REPO_ROOT"
pass "installed $("$VENV/bin/junction" --version)"

step "2/5 — Discovery -> agent-graph.yml (schema v2.0) -> six scaffolded agents -> generated Terraform"
"$VENV/bin/junction" --discover --defaults --agent claude-code --cloud gcp \
  --domain "$DOMAIN" --target "$TARGET" --yes
GRAPH="$TARGET/.github/config/agent-graph.yml"
"$VENV/bin/junction" --validate-graph "$GRAPH"
[ "$(ls "$TARGET/.claude/agents" | wc -l)" -eq 6 ] || fail "expected 6 agent files, found $(ls "$TARGET/.claude/agents" | wc -l)"
pass "graph valid, 6 agents scaffolded for domain=$DOMAIN"

# ─── Stage 2: the Terraform is generated by the bootstrap itself ────────────────

step "3/5 — Verify generated Terraform (store-*.tf / platform-*.tf / service-*.tf)"
[ -d "$TARGET/infra" ] || fail "expected $TARGET/infra to exist — terraform_generator.py did not run"
[ -f "$TARGET/infra/tfvars/dv.tfvars" ] || fail "expected infra/tfvars/dv.tfvars to exist"
pass "infra/ generated ($(ls "$TARGET/infra"/*.tf | wc -l) .tf files, $(ls "$TARGET/infra/tfvars" | wc -l) tfvars files)"

# ─── Stage 3: terraform init / fmt / validate ───────────────────────────────────

step "4/5 — terraform init + fmt -check + validate (real hashicorp/google provider schema)"
cd "$TARGET/infra"
"$TERRAFORM_BIN" init -backend=false -input=false >/tmp/tf-init.log 2>&1 \
  || { cat /tmp/tf-init.log; fail "terraform init failed"; }
"$TERRAFORM_BIN" fmt -check -recursive \
  || fail "terraform fmt found unformatted files (run 'terraform fmt' in $TARGET/infra)"
# `terraform validate -json` exits non-zero when the config is invalid, and it
# always emits valid JSON on stdout either way — capture with set +e so a real
# failure doesn't kill the script via `set -e` before we can report it properly.
set +e
VALIDATE_JSON="$("$TERRAFORM_BIN" validate -json)"
set -e
VALID="$(echo "$VALIDATE_JSON" | python3 -c 'import json,sys; print(json.load(sys.stdin)["valid"])')"
ERRORS="$(echo "$VALIDATE_JSON" | python3 -c 'import json,sys; print(json.load(sys.stdin)["error_count"])')"
if [ "$VALID" != "True" ]; then
  echo "$VALIDATE_JSON" | python3 -c 'import json,sys; [print("-", d["severity"], d["summary"]) for d in json.load(sys.stdin)["diagnostics"]]'
  fail "terraform validate failed ($ERRORS errors)"
fi
pass "terraform validate: 0 errors"

# ─── Stage 4: terraform plan ────────────────────────────────────────────────────

step "5/5 — terraform plan"
PLAN_ARGS=(-input=false -var-file=tfvars/dv.tfvars)
[ -n "$PROJECT_ID" ] && PLAN_ARGS+=(-var "project_id=$PROJECT_ID")
if [ -n "$PROJECT_ID" ]; then
  echo "Real project given (-p $PROJECT_ID) — attempting a real plan. Needs:"
  echo "  gcloud auth application-default login"
  set +e
  PLAN_OUTPUT="$("$TERRAFORM_BIN" plan "${PLAN_ARGS[@]}" 2>&1)"
  PLAN_STATUS=$?
  set -e
  echo "$PLAN_OUTPUT"
  [ $PLAN_STATUS -eq 0 ] && pass "terraform plan succeeded against a real project" \
    || fail "terraform plan failed against a real project — see output above"
else
  set +e
  PLAN_OUTPUT="$("$TERRAFORM_BIN" plan "${PLAN_ARGS[@]}" 2>&1)"
  PLAN_STATUS=$?
  set -e
  if [ $PLAN_STATUS -ne 0 ] && echo "$PLAN_OUTPUT" | grep -qi "could not find default credentials"; then
    pass "plan stopped at the expected boundary: no real GCP credentials (pass -p <project> to go further)"
  elif [ $PLAN_STATUS -eq 0 ]; then
    echo "$PLAN_OUTPUT" | tail -20
    pass "plan succeeded (ADC already configured on this machine)"
  else
    echo "$PLAN_OUTPUT" | tail -30
    fail "plan failed for a reason OTHER than missing credentials — this is a real bug, not the expected boundary"
  fi
fi

echo
echo "════════════════════════════════════════════════════════════════"
echo "  Discovery → graph → agents: automated, verified."
echo "  Terraform: generated by junction/terraform_generator.py from the"
echo "             same discovery answers, then validated for real."
echo "             See docs/wiki/Roadmap-and-Open-Items.md #7."
echo "════════════════════════════════════════════════════════════════"
